import jsPDF from "jspdf";

export const generatePDF = (
  formData: any,
  predictedPrice: number
) => {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("AI-Based Chennai House Price Prediction Report", 20, 20);

  doc.setFontSize(12);

  let y = 40;

  doc.text(`Location: ${formData.area}`, 20, y);
  y += 10;

  doc.text(`Area: ${formData.intSqft} sq.ft`, 20, y);
  y += 10;

  doc.text(`Bedrooms: ${formData.nBedroom}`, 20, y);
  y += 10;

  doc.text(`Bathrooms: ${formData.nBathroom}`, 20, y);
  y += 10;

  doc.text(`Property Age: ${formData.propertyAge} Years`, 20, y);
  y += 10;

  doc.text(`Parking: ${formData.parkFacil}`, 20, y);
  y += 10;

  doc.text(`Furnishing: ${formData.furnishingStatus}`, 20, y);
  y += 10;

  doc.text(`Water Source: ${formData.waterSource}`, 20, y);
  y += 20;

  const formattedPrice =
    predictedPrice >= 10000000
      ? `${(predictedPrice / 10000000).toFixed(2)} Crore`
      : `${(predictedPrice / 100000).toFixed(2)} Lakh`;

  doc.setFontSize(16);
  doc.text(`Predicted Price: ${formattedPrice}`, 20, y);

  y += 20;

  doc.setFontSize(10);
  doc.text(
    "Generated by Chennai House Price Prediction System",
    20,
    y
  );

  doc.save("House_Price_Report.pdf");
};